//ERROR
export const SET_ERRORS = "SET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

//COUNTRIES
export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES";
export const GET_ALL_CAPITALS = "GET_ALL_CAPITALS";
export const GET_COUNTRY_BY_NAME = "GET_COUNTRY_BY_NAME";
export const SEARCH_BY_NAME = "SEARCH_BY_NAME";
export const SEARCH_BY_CAPITAL = "SEARCH_BY_CAPITAL";

export const CLEAR_DATA = "CLEAR_DATA";

//UI
export const SET_COMPONENT_TO_RENDER = "SET_COMPONENT_TO_RENDER";
